//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Model.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKING
    {
        public int ID { get; set; }
        public Nullable<int> ROOMID { get; set; }
        public Nullable<int> CUSID { get; set; }
        public string CHECKINTIME { get; set; }
        public string CHECKOUTTIME { get; set; }
        public string BOOKINGDATE { get; set; }
        public Nullable<int> EMPID { get; set; }
        public Nullable<bool> STATUS { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual ROOM ROOM { get; set; }
    }
}
