//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Model.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERDETAIL
    {
        public int ID { get; set; }
        public Nullable<int> ORDERID { get; set; }
        public Nullable<double> PRICE { get; set; }
        public Nullable<double> DISCOUNT { get; set; }
        public string date { get; set; }
        public Nullable<int> EMPID { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual SRVORDER SRVORDER { get; set; }
    }
}
