//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Model.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHIFT
    {
        public int ID { get; set; }
        public string SHIFTNAME { get; set; }
        public string STARTTIME { get; set; }
        public string ENDTIME { get; set; }
        public Nullable<int> EMPID { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
