//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Model.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRVORDER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SRVORDER()
        {
            this.ORDERDETAILs = new HashSet<ORDERDETAIL>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CUSID { get; set; }
        public Nullable<int> SRVID { get; set; }
        public Nullable<int> ROOMID { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public string NOTE { get; set; }
        public Nullable<bool> PAYMENTSTATUS { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERDETAIL> ORDERDETAILs { get; set; }
        public virtual ROOM ROOM { get; set; }
        public virtual SERVICE SERVICE { get; set; }
    }
}
